title: Studio Genna & Associati
baseURL: /
params:
  palette: blue
  palettes:
    blue:
      sass:
        accent1: '#4167a6'
        accent2: '#3f8eb3'
        accent3: '#4ca07e'
        bg: '#253149'
    green:
      sass:
        accent1: '#2e9692'
        accent2: '#3aa4ca'
        accent3: '#b84d50'
        bg: '#20313d'
    purple:
      sass:
        accent1: '#5e42a6'
        accent2: '#5052b5'
        accent3: '#b74e91'
        bg: '#312450'
    rosso:
      sass:
        accent1: '#b11a21'
        accent2: '#e0474c'
        accent3: '#7ab8d6'
        bg: '#f1f0ee'
menu:
  main:
    - identifier: '1'
      name: Uno
      url: 'https://www.google.it/search?&q=italia+1'
    - identifier: '2'
      name: Due
      url: 'https://www.google.it/search?&q=canele+2+marsala'
disableKinds:
  - RSS
